name: .NET

on:
  push:
    branches: [ main, 'dev*', 'feat*/**', 'feature/**', 'fix/**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SLN_FILE_PATH:  ./net6-cicd-az.sln
      COMMIT_HASH_SHORT: "`git rev-parse --short HEAD`"

    steps:
      - uses: actions/checkout@v3

      # Echo the workspace; useful for debugging workflow
      - name: Echo Workspace
        run: echo $GITHUB_WORKSPACE \
          echo $GITHUB_REF_NAME \
          echo $GITHUB_SHA \ 
          echo $COMMIT_HASH_SHORT

      - name: show short sha 1
        run: \
          echo "${GITHUB_SHA} | cut -c1-8"

      - name: Setup .NET 6.0 SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ${{ env.SLN_FILE_PATH }}
      - name: Build
        run: dotnet build --no-restore ${{ env.SLN_FILE_PATH }}
      - name: Test
        run: dotnet test --no-build --verbosity normal ${{ env.SLN_FILE_PATH }}
