name: .NET

on:
  push:
    branches: [ main, 'dev*', 'feat*/**', 'feature/**', 'fix/**' ]
    paths-ignore: '.github/workflows/*'

  pull_request:
    branches: [ main ]
    paths-ignore: '.github/workflows/*'
    
  workflow_dispatch: {}
  

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SLN_FILE_PATH:  ./net6-cicd-az.sln

    steps:
      - name: Set 8-char SHA
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      # Echo the workspace; useful for debugging workflow
      - name: Echo Workspace details
        run: echo "GITHUB_WORKSPACE:" $GITHUB_WORKSPACE \
          "GITHUB_REF_NAME:" $GITHUB_REF_NAME  \
          "GITHUB_SHA:" $GITHUB_SHA  \
          "SHORT_SHA:" $SHORT_SHA

      - uses: actions/checkout@v3

      - name: Setup .NET 6.0 SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ${{ env.SLN_FILE_PATH }}
      - name: Build
        run: dotnet build --no-restore ${{ env.SLN_FILE_PATH }}
      - name: Test
        run: dotnet test --no-build --verbosity normal ${{ env.SLN_FILE_PATH }}
      - name: Collect code coverage
        run: make cover
