name: Show Environment Info

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: 'Target Azure Environment'
        type: choice
        options:
        - QA
        - PROD
        default: QA
        required: true

### Env global to script 
env:
  BUILD_CONFIG: 'Release'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.inputs.target-env == 'QA'
        name: Set env for QA
        run: echo "You selected QA"
      - if: github.event.inputs.target-env == 'PROD'
        name: Set env for PROD
        run: echo "You selected PROD"

      - name: GitHub values
        run: |
          echo "github.event.inputs.target-env ${{ github.event.inputs.target-env }}"
          echo "github.actor ${{github.actor}}"
          echo "github.event_name ${{github.event_name}}"
          echo "github.ref ${{github.ref}}"
          echo "github.ref_name ${{github.ref_name}}"
          echo "github.ref_type ${{github.ref_type}}"
          echo "github.path ${{github.path}}"
          echo "github.sha ${{github.sha}}"
          echo "github.workspace ${{github.workspace}}"

      - name: Environment values
        run: |
          echo "env.GITHUB_ENV ${{ env.GITHUB_ENV }}"
          echo "GITHUB_ENV $GITHUB_ENV"
